-- 002_raw.sql: append-only RAW tables, loaded by n8n once per run.
-- Safe to re-run: CREATE TABLE IF NOT EXISTS never touches existing data. Never change
-- these to CREATE OR REPLACE, which would drop every loaded row.
-- Append-only is enforced by grants: GTM_LOADER can INSERT and SELECT, nothing else.

USE ROLE SYSADMIN;
USE DATABASE GTM_DEMO;
USE SCHEMA RAW;

-- One row per enrichment attempt as reported by the enrichment service. n8n may load the
-- same event twice after a retry; ANALYTICS.V_ENRICHMENT_EVENTS keeps one row per EVENT_ID.
-- PAYLOAD is plain text: the n8n insert binds values, and a VALUES clause cannot call
-- PARSE_JSON, so the JSON is parsed in the view instead.
CREATE TABLE IF NOT EXISTS RAW.ENRICHMENT_EVENTS (
  EVENT_ID         VARCHAR       NOT NULL COMMENT 'Unique per event; generated by n8n',
  LEAD_ID          VARCHAR       NOT NULL COMMENT 'Salesforce Lead Id',
  EVENT_TYPE       VARCHAR       NOT NULL COMMENT 'enriched, duplicate or failed',
  RULES_VERSION    VARCHAR                COMMENT 'Scoring rules version, e.g. 2026.10.1',
  MODEL            VARCHAR                COMMENT 'Model or inference profile ID; null if no model was called',
  SCORE            NUMBER(3, 0),
  TIER             VARCHAR                COMMENT 'A, B or C',
  LATENCY_MS       NUMBER(10, 0),
  INPUT_TOKENS     NUMBER(10, 0),
  OUTPUT_TOKENS    NUMBER(10, 0),
  COST_USD         NUMBER(12, 6),
  SIGNALS_KEPT     NUMBER(3, 0),
  SIGNALS_DROPPED  NUMBER(3, 0),
  PAYLOAD          VARCHAR                COMMENT 'Service response (or error) as JSON text; parsed in ANALYTICS.V_ENRICHMENT_EVENTS',
  OCCURRED_AT      TIMESTAMP_TZ  NOT NULL COMMENT 'When the enrichment happened',
  LOADED_AT        TIMESTAMP_TZ  NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT 'When the row was inserted'
)
COMMENT = 'Append-only: one row per enrichment event. Never updated or deleted.';

-- The Salesforce state of each lead, copied once per n8n run. Every run appends a new
-- snapshot; ANALYTICS.V_LEAD_CURRENT picks the latest per lead.
CREATE TABLE IF NOT EXISTS RAW.SF_LEAD_SNAPSHOT (
  LEAD_ID           VARCHAR       NOT NULL COMMENT 'Salesforce Lead Id',
  STATUS            VARCHAR                COMMENT 'Enrichment_Status__c',
  TIER              VARCHAR                COMMENT 'ICP_Tier__c',
  SCORE             NUMBER(3, 0)           COMMENT 'ICP_Score__c',
  COMPANY_TYPE      VARCHAR                COMMENT 'Company_Type__c',
  EMPLOYEE_BAND     VARCHAR                COMMENT 'Employee_Band__c',
  ENRICHED_AT       TIMESTAMP_TZ           COMMENT 'Enriched_At__c',
  REVIEWED_AT       TIMESTAMP_TZ           COMMENT 'Reviewed_At__c',
  REVIEWED_BY       VARCHAR(80)            COMMENT 'Reviewed_By__c',
  SF_LAST_MODIFIED  TIMESTAMP_TZ           COMMENT 'Lead LastModifiedDate',
  SNAPSHOT_AT       TIMESTAMP_TZ  NOT NULL COMMENT 'When n8n read the lead from Salesforce'
)
COMMENT = 'Append-only: one row per lead per n8n run. Never updated or deleted.';
